/* 
 * Autogenerated by rtgen. Licenced under the terms of the GPL.
 */

#include "vectors.h"
#include <math.h>


void cross_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs)
{
	out->x = ((lhs->y * rhs->z) - (lhs->z * rhs->y));
	out->y = ((lhs->z * rhs->x) - (lhs->x * rhs->z));
	out->z = ((lhs->x * rhs->y) - (lhs->y * rhs->x));

}

void cross_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs)
{
	out->x = ((lhs->y * rhs->z) - (lhs->z * rhs->y));
	out->y = ((lhs->z * rhs->x) - (lhs->x * rhs->z));
	out->z = ((lhs->x * rhs->y) - (lhs->y * rhs->x));

}

void set_vec4d_component_val(const vec4d *v, int c, double newval)
{
	((float *)v)[c] = newval;

}

void set_vec4f_component_val(const vec4f *v, int c, float newval)
{
	((float *)v)[c] = newval;

}

void set_vec3d_component_val(const vec3d *v, int c, double newval)
{
	((float *)v)[c] = newval;

}

void set_vec3f_component_val(const vec3f *v, int c, float newval)
{
	((float *)v)[c] = newval;

}

void set_vec2d_component_val(const vec2d *v, int c, double newval)
{
	((float *)v)[c] = newval;

}

void set_vec2f_component_val(const vec2f *v, int c, float newval)
{
	((float *)v)[c] = newval;

}

void make_vec2d(vec2d *v, double x, double y)
{
	v->x = x;
	v->y = y;

}

void make_vec2f(vec2f *v, float x, float y)
{
	v->x = x;
	v->y = y;

}

double vec4d_component_val(const vec4d *v, int c)
{
	return ((float *)v)[c];

}

float vec4f_component_val(const vec4f *v, int c)
{
	return ((float *)v)[c];

}

void make_vec3d(vec3d *v, double x, double y, double z)
{
	v->x = x;
	v->y = y;
	v->z = z;

}

void make_vec3f(vec3f *v, float x, float y, float z)
{
	v->x = x;
	v->y = y;
	v->z = z;

}

double vec3d_component_val(const vec3d *v, int c)
{
	return ((float *)v)[c];

}

float vec3f_component_val(const vec3f *v, int c)
{
	return ((float *)v)[c];

}

void make_vec4d(vec4d *v, double x, double y, double z, double w)
{
	v->x = x;
	v->y = y;
	v->z = z;
	v->w = w;

}

void make_vec4f(vec4f *v, float x, float y, float z, float w)
{
	v->x = x;
	v->y = y;
	v->z = z;
	v->w = w;

}

double vec2d_component_val(const vec2d *v, int c)
{
	return ((float *)v)[c];

}

float vec2f_component_val(const vec2f *v, int c)
{
	return ((float *)v)[c];

}

void copy_vec2d(vec2d *out, const vec2d *in)
{
	out->x = in->x;
	out->y = in->y;

}

void copy_vec2f(vec2f *out, const vec2f *in)
{
	out->x = in->x;
	out->y = in->y;

}

void div_vec4d_by_scalar(vec4d *out, const vec4d *lhs, double rhs)
{
	out->x = (lhs->x / rhs);
	out->y = (lhs->y / rhs);
	out->z = (lhs->z / rhs);
	out->w = (lhs->w / rhs);

}

void div_vec4f_by_scalar(vec4f *out, const vec4f *lhs, float rhs)
{
	out->x = (lhs->x / rhs);
	out->y = (lhs->y / rhs);
	out->z = (lhs->z / rhs);
	out->w = (lhs->w / rhs);

}

void copy_vec3d(vec3d *out, const vec3d *in)
{
	out->x = in->x;
	out->y = in->y;
	out->z = in->z;

}

void copy_vec3f(vec3f *out, const vec3f *in)
{
	out->x = in->x;
	out->y = in->y;
	out->z = in->z;

}

void div_vec3d_by_scalar(vec3d *out, const vec3d *lhs, double rhs)
{
	out->x = (lhs->x / rhs);
	out->y = (lhs->y / rhs);
	out->z = (lhs->z / rhs);

}

void div_vec3f_by_scalar(vec3f *out, const vec3f *lhs, float rhs)
{
	out->x = (lhs->x / rhs);
	out->y = (lhs->y / rhs);
	out->z = (lhs->z / rhs);

}

void copy_vec4d(vec4d *out, const vec4d *in)
{
	out->x = in->x;
	out->y = in->y;
	out->z = in->z;
	out->w = in->w;

}

void copy_vec4f(vec4f *out, const vec4f *in)
{
	out->x = in->x;
	out->y = in->y;
	out->z = in->z;
	out->w = in->w;

}

void div_vec2d_by_scalar(vec2d *out, const vec2d *lhs, double rhs)
{
	out->x = (lhs->x / rhs);
	out->y = (lhs->y / rhs);

}

void div_vec2f_by_scalar(vec2f *out, const vec2f *lhs, float rhs)
{
	out->x = (lhs->x / rhs);
	out->y = (lhs->y / rhs);

}

bool equal_under_eps_vec2d(const vec2d *a, const vec2d *b, double eps)
{
	if (fabs((a->x - b->x)) > eps)
		return false;
	if (fabs((a->y - b->y)) > eps)
		return false;
	return true;

}

bool equal_under_eps_vec2f(const vec2f *a, const vec2f *b, float eps)
{
	if (fabsf((a->x - b->x)) > eps)
		return false;
	if (fabsf((a->y - b->y)) > eps)
		return false;
	return true;

}

void mul_vec4d_by_scalar(vec4d *out, const vec4d *lhs, double rhs)
{
	out->x = (lhs->x * rhs);
	out->y = (lhs->y * rhs);
	out->z = (lhs->z * rhs);
	out->w = (lhs->w * rhs);

}

void mul_vec4f_by_scalar(vec4f *out, const vec4f *lhs, float rhs)
{
	out->x = (lhs->x * rhs);
	out->y = (lhs->y * rhs);
	out->z = (lhs->z * rhs);
	out->w = (lhs->w * rhs);

}

bool equal_under_eps_vec3d(const vec3d *a, const vec3d *b, double eps)
{
	if (fabs((a->x - b->x)) > eps)
		return false;
	if (fabs((a->y - b->y)) > eps)
		return false;
	if (fabs((a->z - b->z)) > eps)
		return false;
	return true;

}

bool equal_under_eps_vec3f(const vec3f *a, const vec3f *b, float eps)
{
	if (fabsf((a->x - b->x)) > eps)
		return false;
	if (fabsf((a->y - b->y)) > eps)
		return false;
	if (fabsf((a->z - b->z)) > eps)
		return false;
	return true;

}

void mul_vec3d_by_scalar(vec3d *out, const vec3d *lhs, double rhs)
{
	out->x = (lhs->x * rhs);
	out->y = (lhs->y * rhs);
	out->z = (lhs->z * rhs);

}

void mul_vec3f_by_scalar(vec3f *out, const vec3f *lhs, float rhs)
{
	out->x = (lhs->x * rhs);
	out->y = (lhs->y * rhs);
	out->z = (lhs->z * rhs);

}

bool equal_under_eps_vec4d(const vec4d *a, const vec4d *b, double eps)
{
	if (fabs((a->x - b->x)) > eps)
		return false;
	if (fabs((a->y - b->y)) > eps)
		return false;
	if (fabs((a->z - b->z)) > eps)
		return false;
	if (fabs((a->w - b->w)) > eps)
		return false;
	return true;

}

bool equal_under_eps_vec4f(const vec4f *a, const vec4f *b, float eps)
{
	if (fabsf((a->x - b->x)) > eps)
		return false;
	if (fabsf((a->y - b->y)) > eps)
		return false;
	if (fabsf((a->z - b->z)) > eps)
		return false;
	if (fabsf((a->w - b->w)) > eps)
		return false;
	return true;

}

void mul_vec2d_by_scalar(vec2d *out, const vec2d *lhs, double rhs)
{
	out->x = (lhs->x * rhs);
	out->y = (lhs->y * rhs);

}

void mul_vec2f_by_scalar(vec2f *out, const vec2f *lhs, float rhs)
{
	out->x = (lhs->x * rhs);
	out->y = (lhs->y * rhs);

}

double dot_vec2d(const vec2d *lhs, const vec2d *rhs)
{
	double sum = (lhs->x * rhs->x);
	sum = (sum + (lhs->y * rhs->y));
	return sum;

}

float dot_vec2f(const vec2f *lhs, const vec2f *rhs)
{
	float sum = (lhs->x * rhs->x);
	sum = (sum + (lhs->y * rhs->y));
	return sum;

}

void div_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs)
{
	out->x = (lhs->x / rhs->x);
	out->y = (lhs->y / rhs->y);
	out->z = (lhs->z / rhs->z);
	out->w = (lhs->w / rhs->w);

}

void div_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs)
{
	out->x = (lhs->x / rhs->x);
	out->y = (lhs->y / rhs->y);
	out->z = (lhs->z / rhs->z);
	out->w = (lhs->w / rhs->w);

}

double dot_vec3d(const vec3d *lhs, const vec3d *rhs)
{
	double sum = (lhs->x * rhs->x);
	sum = (sum + (lhs->y * rhs->y));
	sum = (sum + (lhs->z * rhs->z));
	return sum;

}

float dot_vec3f(const vec3f *lhs, const vec3f *rhs)
{
	float sum = (lhs->x * rhs->x);
	sum = (sum + (lhs->y * rhs->y));
	sum = (sum + (lhs->z * rhs->z));
	return sum;

}

void div_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs)
{
	out->x = (lhs->x / rhs->x);
	out->y = (lhs->y / rhs->y);
	out->z = (lhs->z / rhs->z);

}

void div_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs)
{
	out->x = (lhs->x / rhs->x);
	out->y = (lhs->y / rhs->y);
	out->z = (lhs->z / rhs->z);

}

double dot_vec4d(const vec4d *lhs, const vec4d *rhs)
{
	double sum = (lhs->x * rhs->x);
	sum = (sum + (lhs->y * rhs->y));
	sum = (sum + (lhs->z * rhs->z));
	sum = (sum + (lhs->w * rhs->w));
	return sum;

}

float dot_vec4f(const vec4f *lhs, const vec4f *rhs)
{
	float sum = (lhs->x * rhs->x);
	sum = (sum + (lhs->y * rhs->y));
	sum = (sum + (lhs->z * rhs->z));
	sum = (sum + (lhs->w * rhs->w));
	return sum;

}

void div_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs)
{
	out->x = (lhs->x / rhs->x);
	out->y = (lhs->y / rhs->y);

}

void div_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs)
{
	out->x = (lhs->x / rhs->x);
	out->y = (lhs->y / rhs->y);

}

double length_of_vec2d(const vec2d *v)
{
	return sqrt(dot_vec2d(v, v));

}

float length_of_vec2f(const vec2f *v)
{
	return sqrtf(dot_vec2f(v, v));

}

void mul_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs)
{
	out->x = (lhs->x * rhs->x);
	out->y = (lhs->y * rhs->y);
	out->z = (lhs->z * rhs->z);
	out->w = (lhs->w * rhs->w);

}

void mul_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs)
{
	out->x = (lhs->x * rhs->x);
	out->y = (lhs->y * rhs->y);
	out->z = (lhs->z * rhs->z);
	out->w = (lhs->w * rhs->w);

}

double length_of_vec3d(const vec3d *v)
{
	return sqrt(dot_vec3d(v, v));

}

float length_of_vec3f(const vec3f *v)
{
	return sqrtf(dot_vec3f(v, v));

}

void mul_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs)
{
	out->x = (lhs->x * rhs->x);
	out->y = (lhs->y * rhs->y);
	out->z = (lhs->z * rhs->z);

}

void mul_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs)
{
	out->x = (lhs->x * rhs->x);
	out->y = (lhs->y * rhs->y);
	out->z = (lhs->z * rhs->z);

}

double length_of_vec4d(const vec4d *v)
{
	return sqrt(dot_vec4d(v, v));

}

float length_of_vec4f(const vec4f *v)
{
	return sqrtf(dot_vec4f(v, v));

}

void mul_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs)
{
	out->x = (lhs->x * rhs->x);
	out->y = (lhs->y * rhs->y);

}

void mul_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs)
{
	out->x = (lhs->x * rhs->x);
	out->y = (lhs->y * rhs->y);

}

void normalize_vec2d(vec2d *v)
{
	div_vec2d_by_scalar(v, v, length_of_vec2d(v));

}

void normalize_vec2f(vec2f *v)
{
	div_vec2f_by_scalar(v, v, length_of_vec2f(v));

}

void sub_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs)
{
	out->x = (lhs->x - rhs->x);
	out->y = (lhs->y - rhs->y);
	out->z = (lhs->z - rhs->z);
	out->w = (lhs->w - rhs->w);

}

void sub_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs)
{
	out->x = (lhs->x - rhs->x);
	out->y = (lhs->y - rhs->y);
	out->z = (lhs->z - rhs->z);
	out->w = (lhs->w - rhs->w);

}

void normalize_vec3d(vec3d *v)
{
	div_vec3d_by_scalar(v, v, length_of_vec3d(v));

}

void normalize_vec3f(vec3f *v)
{
	div_vec3f_by_scalar(v, v, length_of_vec3f(v));

}

void sub_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs)
{
	out->x = (lhs->x - rhs->x);
	out->y = (lhs->y - rhs->y);
	out->z = (lhs->z - rhs->z);

}

void sub_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs)
{
	out->x = (lhs->x - rhs->x);
	out->y = (lhs->y - rhs->y);
	out->z = (lhs->z - rhs->z);

}

void normalize_vec4d(vec4d *v)
{
	div_vec4d_by_scalar(v, v, length_of_vec4d(v));

}

void normalize_vec4f(vec4f *v)
{
	div_vec4f_by_scalar(v, v, length_of_vec4f(v));

}

void sub_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs)
{
	out->x = (lhs->x - rhs->x);
	out->y = (lhs->y - rhs->y);

}

void sub_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs)
{
	out->x = (lhs->x - rhs->x);
	out->y = (lhs->y - rhs->y);

}

void add_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs)
{
	out->x = (lhs->x + rhs->x);
	out->y = (lhs->y + rhs->y);

}

void add_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs)
{
	out->x = (lhs->x + rhs->x);
	out->y = (lhs->y + rhs->y);

}

void add_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs)
{
	out->x = (lhs->x + rhs->x);
	out->y = (lhs->y + rhs->y);
	out->z = (lhs->z + rhs->z);
	out->w = (lhs->w + rhs->w);

}

void add_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs)
{
	out->x = (lhs->x + rhs->x);
	out->y = (lhs->y + rhs->y);
	out->z = (lhs->z + rhs->z);
	out->w = (lhs->w + rhs->w);

}

void add_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs)
{
	out->x = (lhs->x + rhs->x);
	out->y = (lhs->y + rhs->y);
	out->z = (lhs->z + rhs->z);

}

void add_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs)
{
	out->x = (lhs->x + rhs->x);
	out->y = (lhs->y + rhs->y);
	out->z = (lhs->z + rhs->z);

}

