/* 
 * Autogenerated by rtgen. Licenced under the terms of the GPL.
 */

#ifndef __CGEN_vectors_H__
#define __CGEN_vectors_H__

#ifndef __cplusplus
#include <stdbool.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif


typedef struct vec2d {
	double x;
	double y;
#ifdef __cplusplus
    vec2d() {}
    vec2d(double x, double y) : x(x), y(y) {}
#endif
} vec2d;


typedef struct vec2f {
	float x;
	float y;
#ifdef __cplusplus
    vec2f() {}
    vec2f(float x, float y) : x(x), y(y) {}
#endif
} vec2f;


typedef struct vec2i {
	int x;
	int y;
#ifdef __cplusplus
    vec2i() {}
    vec2i(int x, int y) : x(x), y(y) {}
#endif
} vec2i;


typedef struct vec3d {
	double x;
	double y;
	double z;
#ifdef __cplusplus
    vec3d() {}
    vec3d(double x, double y, double z) : x(x), y(y), z(z) {}
#endif
} vec3d;


typedef struct vec3f {
	float x;
	float y;
	float z;
#ifdef __cplusplus
    vec3f() {}
    vec3f(float x, float y, float z) : x(x), y(y), z(z) {}
#endif
} vec3f;


typedef struct vec3i {
	int x;
	int y;
	int z;
#ifdef __cplusplus
    vec3i() {}
    vec3i(int x, int y, int z) : x(x), y(y), z(z) {}
#endif
} vec3i;


typedef struct vec4d {
	double x;
	double y;
	double z;
	double w;
#ifdef __cplusplus
    vec4d() {}
    vec4d(double x, double y, double z, double w) : x(x), y(y), z(z), w(w) {}
#endif
} vec4d;

typedef struct vec4i {
	int x;
	int y;
	int z;
	int w;
#ifdef __cplusplus
    vec4i() {}
    vec4i(int x, int y, int z, int w) : x(x), y(y), z(z), w(w) {}
#endif
} vec4i;


typedef struct vec4f {
	float x;
	float y;
	float z;
	float w;
#ifdef __cplusplus
    vec4f() {}
    vec4f(float x, float y, float z, float w) : x(x), y(y), z(z), w(w) {}
#endif
} vec4f;


void cross_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs);
void cross_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs);
void set_vec4d_component_val(const vec4d *v, int c, double newval);
void set_vec4f_component_val(const vec4f *v, int c, float newval);
void set_vec3d_component_val(const vec3d *v, int c, double newval);
void set_vec3f_component_val(const vec3f *v, int c, float newval);
void set_vec2d_component_val(const vec2d *v, int c, double newval);
void set_vec2f_component_val(const vec2f *v, int c, float newval);
void make_vec2d(vec2d *v, double x, double y);
void make_vec2f(vec2f *v, float x, float y);
double vec4d_component_val(const vec4d *v, int c);
float vec4f_component_val(const vec4f *v, int c);
void make_vec3d(vec3d *v, double x, double y, double z);
void make_vec3f(vec3f *v, float x, float y, float z);
double vec3d_component_val(const vec3d *v, int c);
float vec3f_component_val(const vec3f *v, int c);
void make_vec4d(vec4d *v, double x, double y, double z, double w);
void make_vec4f(vec4f *v, float x, float y, float z, float w);
double vec2d_component_val(const vec2d *v, int c);
float vec2f_component_val(const vec2f *v, int c);
void copy_vec2d(vec2d *out, const vec2d *in);
void copy_vec2f(vec2f *out, const vec2f *in);
void div_vec4d_by_scalar(vec4d *out, const vec4d *lhs, double rhs);
void div_vec4f_by_scalar(vec4f *out, const vec4f *lhs, float rhs);
void copy_vec3d(vec3d *out, const vec3d *in);
void copy_vec3f(vec3f *out, const vec3f *in);
void div_vec3d_by_scalar(vec3d *out, const vec3d *lhs, double rhs);
void div_vec3f_by_scalar(vec3f *out, const vec3f *lhs, float rhs);
void copy_vec4d(vec4d *out, const vec4d *in);
void copy_vec4f(vec4f *out, const vec4f *in);
void div_vec2d_by_scalar(vec2d *out, const vec2d *lhs, double rhs);
void div_vec2f_by_scalar(vec2f *out, const vec2f *lhs, float rhs);
bool equal_under_eps_vec2d(const vec2d *a, const vec2d *b, double eps);
bool equal_under_eps_vec2f(const vec2f *a, const vec2f *b, float eps);
void mul_vec4d_by_scalar(vec4d *out, const vec4d *lhs, double rhs);
void mul_vec4f_by_scalar(vec4f *out, const vec4f *lhs, float rhs);
bool equal_under_eps_vec3d(const vec3d *a, const vec3d *b, double eps);
bool equal_under_eps_vec3f(const vec3f *a, const vec3f *b, float eps);
void mul_vec3d_by_scalar(vec3d *out, const vec3d *lhs, double rhs);
void mul_vec3f_by_scalar(vec3f *out, const vec3f *lhs, float rhs);
bool equal_under_eps_vec4d(const vec4d *a, const vec4d *b, double eps);
bool equal_under_eps_vec4f(const vec4f *a, const vec4f *b, float eps);
void mul_vec2d_by_scalar(vec2d *out, const vec2d *lhs, double rhs);
void mul_vec2f_by_scalar(vec2f *out, const vec2f *lhs, float rhs);
double dot_vec2d(const vec2d *lhs, const vec2d *rhs);
float dot_vec2f(const vec2f *lhs, const vec2f *rhs);
void div_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs);
void div_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs);
double dot_vec3d(const vec3d *lhs, const vec3d *rhs);
float dot_vec3f(const vec3f *lhs, const vec3f *rhs);
void div_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs);
void div_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs);
double dot_vec4d(const vec4d *lhs, const vec4d *rhs);
float dot_vec4f(const vec4f *lhs, const vec4f *rhs);
void div_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs);
void div_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs);
double length_of_vec2d(const vec2d *v);
float length_of_vec2f(const vec2f *v);
void mul_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs);
void mul_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs);
double length_of_vec3d(const vec3d *v);
float length_of_vec3f(const vec3f *v);
void mul_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs);
void mul_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs);
double length_of_vec4d(const vec4d *v);
float length_of_vec4f(const vec4f *v);
void mul_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs);
void mul_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs);
void normalize_vec2d(vec2d *v);
void normalize_vec2f(vec2f *v);
void sub_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs);
void sub_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs);
void normalize_vec3d(vec3d *v);
void normalize_vec3f(vec3f *v);
void sub_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs);
void sub_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs);
void normalize_vec4d(vec4d *v);
void normalize_vec4f(vec4f *v);
void sub_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs);
void sub_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs);
void add_components_vec2d(vec2d *out, const vec2d *lhs, const vec2d *rhs);
void add_components_vec2f(vec2f *out, const vec2f *lhs, const vec2f *rhs);
void add_components_vec4d(vec4d *out, const vec4d *lhs, const vec4d *rhs);
void add_components_vec4f(vec4f *out, const vec4f *lhs, const vec4f *rhs);
void add_components_vec3d(vec3d *out, const vec3d *lhs, const vec3d *rhs);
void add_components_vec3f(vec3f *out, const vec3f *lhs, const vec3f *rhs);


#ifdef __cplusplus
}

#include "operators.h"

#endif

#endif

